### ISSUE TITLE
Boxes misaligned when width is between 1200px and 992px

### ISSUE THREAD

**Issue by scottopell** [Purdue-CSUSB/usb-website#1]
See screenshot
https://www.dropbox.com/s/pdegvy7748fcath/Screenshot%202015-01-29%2000.40.32.png?dl=0

13" retina display

**Comment by kirbyk** [comment]
I don't know how to fix this, because the line break is causing the issue.

Since this is jekyll generated, there is no easy way to specify that exact element and make the font smaller (to prevent the line break)

Thoughts, @balderfer?
